MODULES+=	error-page-inherit

MODULE_SUMMARY_error_page_inherit=	enable support to error_page_inherit derective in nginx.conf.

MODULE_VERSION_error_page_inherit=	0.01
MODULE_RELEASE_error_page_inherit=	1

MODULE_VERSION_PREFIX_error_page_inherit=$(MODULE_TARGET_PREFIX)

MODULE_NAME_error_page_inherit=	ngx_http_error_page_inherit_module

MODULE_SOURCES_error_page_inherit=	$(GITHUB)/$(MODULE_NAME_error_page_inherit).git

MODULE_CONFARGS_error_page_inherit=	--add-dynamic-module=$(MODULE_NAME_error_page_inherit)

define MODULE_PREP_SOURCES_error_page_inherit
cd %{bdir} \&\& git clone $(MODULE_SOURCES_error_page_inherit)
endef
export MODULE_PREP_SOURCES_error_page_inherit

define MODULE_POST_error_page_inherit
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_error_page_inherit) for $(MODULE_SUMMARY_PREFIX) have been installed.
To enable these modules, add the following to /etc/nginx/nginx.conf
and reload nginx:

    load_module modules/MODULE_NAME_error_page_inherit.so;

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_error_page_inherit
