MODULES+=	include-server

MODULE_SUMMARY_include_server=	enable support to include_server derective in nginx.conf.

MODULE_VERSION_include_server=	0.01
MODULE_RELEASE_include_server=	1

MODULE_VERSION_PREFIX_include_server=$(MODULE_TARGET_PREFIX)

MODULE_NAME_include_server=	ngx_http_include_server_module

MODULE_SOURCES_include_server=	$(GITHUB)/$(MODULE_NAME_include_server).git

MODULE_CONFARGS_include_server=	--add-dynamic-module=$(MODULE_NAME_include_server)

define MODULE_PREP_SOURCES_include_server
cd %{bdir} \&\& git clone $(MODULE_SOURCES_include_server)
endef
export MODULE_PREP_SOURCES_include_server

define MODULE_POST_include_server
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_include_server) for $(MODULE_SUMMARY_PREFIX) have been installed.
To enable these modules, add the following to /etc/nginx/nginx.conf
and reload nginx:

    load_module modules/$(MODULE_NAME_include_server).so;

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_include_server
